version: "3.8"
services: 
  backend:
    image: "backend.jar"
    container_name: "backend.jar"
    ports:
      - "8080:8080"
 
  frontend:
    image: "frontend"
    container_name: "frontend"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start